# Generated by Django 3.2.9 on 2021-12-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='token',
            field=models.CharField(default='eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImNocmlzYW5zdGVhZCIsInNvdXJjZSI6InRyYXZlbGFkbyJ9.9LAxFyRkZ1U-bWFfC3MDtrACRtCx1xLmS4oIKvGuQ60', max_length=500),
            preserve_default=False,
        ),
    ]
