DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS reviews;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE reviews (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  title TEXT NOT NULL,
  rating INTEGER PRIMARY KEY,
  body TEXT NOT NULL,
  latitude INTEGER PRIMARY KEY,
  longitude INTEGER PRIMARY KEY,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);